# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Umich Alexa Team - Audrey
email: dravesr@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  The UM Alex Prize team is applying to compete in Amazon's Alexa
  Prize challenge, where we will create a socialbot to talk to
  Alexa customers and advance the field of conversational AI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryandraves.github.io" # the base hostname & protocol for your site
github_username:  RyanDraves

# Build settings
markdown: kramdown
