# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Umich Alexa Team - Audrey
email: dravesr@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  The UM Alexa Prize team is competing in Amazon's 3rd Alexa
  Prize challenge, where we are working to create a socialbot to talk to
  Alexa customers and advance the field of conversational AI.
baseurl: "RyanDraves-github-io/" # the subpath of your site, e.g. /blog
url: "http://dravesr.pages.umsi.io/" # the base hostname & protocol for your site
github_username:  RyanDraves


# Build settings
markdown: kramdown
# See https://docs.gitlab.com/ee/user/project/pages/getting_started_part_four.html
exclude:
    - vendor
    - "Gemfile"
    - "Gemfile.lock"
encoding: utf-8